name: Build and Push Docker Image

# This section defines how the workflow is triggered.
# `workflow_dispatch` means you have to trigger it manually from GitHub UI.
# This prevents automatic updates when pushing code.

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  build:
    # GitHub will run this job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code from the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using secrets stored in GitHub
      # Make sure you’ve added DOCKER_USERNAME and DOCKER_PASSWORD in repo > Settings > Secrets
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image and push it to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .                      # Directory to build Docker image from
          push: true                      # Set to true to push image after building
          tags: ramos1817/studentmanagement:latest   # Tag used for the image on Docker Hub
        
